rails/config/routes.rb
Rails.application.routes.draw do
  get 'repas/new'

  get 'sessions/new'

  get 'pages/home'
  get 'pages/about'
  root 'pages#home'
  get '/signup', to: 'restos#new'
  post '/signup', to: 'restos#create'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :restos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/app/models/repa.rb
class Repa < ApplicationRecord
end

rails/app/models/resto.rb
class Resto < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :fname, presence: true, length: { maximum: 50 }
  validates :resto, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
        format: { with: VALID_EMAIL_REGEX },
        uniqueness: { case_sensitive: false }
  validates :phone, presence: true, length: { maximum: 15 }
  validates :adresse, presence: true, length: { maximum: 255 }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

rails/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

rails/app/controllers/repas_controller.rb
class RepasController < ApplicationController
  def new
  end
end

rails/app/controllers/restos_controller.rb
class RestosController < ApplicationController
  respond_to :json, :html, only: [:show]

  def show
    @resto = Resto.find(params[:id])
    respond_with(@resto)
  end

  def new
    @resto = Resto.new
  end

  def create
    @resto = Resto.new(resto_params)
    if @resto.save
      log_in @resto
      flash[:sucess] = "nice"
      redirect_to @resto
    else 
      render 'new'
    end
  end

  private

    def resto_params
      params.require(:resto).permit(:name, :fname, :resto,
        :email, :phone, :adresse, :password, :password_confirmation)
    end
end

rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    resto = Resto.find_by(email: params[:session][:email].downcase)
    if resto && resto.authenticate(params[:session][:password])
      log_in resto
      redirect_to resto
      # Log the resto in and redirect to the resto's show page.
    else
      flash[:danger] = 'Invalid email/password combination' # Not quite right!
      # Create an error message.
     render 'new'
    end
  end

  def destroy
    log_out
    flash[:sucess] = "logout succesfuly"
    redirect_to root_url
  end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/pages_helper.rb
module PagesHelper
end

rails/app/helpers/repas_helper.rb
module RepasHelper
end

rails/app/helpers/restos_helper.rb
module RestosHelper
end

rails/app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(resto)
    session[:resto_id] = resto.id
  end

  def current_resto
    @current_resto ||= Resto.find_by(id: session[:resto_id])
  end

  def logged_in?
    !current_resto.nil?
  end

  def log_out
    session.delete(:resto_id)
    @current_user = nil
  end
end

rails/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "raff", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Restos", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profils", current_resto %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raff</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

rails/app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

rails/app/views/pages/home.html.erb
<h1>Pages#home</h1>
<%= image_tag "wallpaper.png", alt: "Mon image", width: "160", height: "90" %>
<p>Find me in app/views/pages/home.html.erb</p>

rails/app/views/repas/new.html.erb
<h1>Repas#new</h1>
<p>Find me in app/views/repas/new.html.erb</p>

rails/app/views/restos/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@resto, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>
	
      <div class='row'>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :fname %>
      <%= f.text_field :fname %>
      </div>

      <div class='row'>
      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>
      </div>

      <div class='row'>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.label :phone %>
      <%= f.text_field :phone %>
      </div>

      <div class='row'>
      <%= f.label :adresse %>
      <%= f.text_field :adresse %>

      <%= f.label :resto %>
      <%= f.text_field :resto %>
      </div>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

rails/app/views/restos/show.html.erb
<%= @resto.name %>, <%= @resto.email %>

rails/app/views/shared/_error_messages.html.erb
<% if @resto.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@resto.errors.count, "error") %>.
    </div>
    <ul>
    <% @resto.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>